.\"     %A%
.\"
.Dd August 11, 2011
.Dt Zzz 8
.Os MASTODON
.Sh NAME
.Nm Zzz
.Nd put your macintosh to sleep
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
program tells power management to put the machine to sleep
.Em now .
.Sh RETURN VALUES
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh BUGS
You don't need to be root to put your mac to sleep.
.Sh AUTHOR
.An David Parsons
.Pq Li orc@pell.chi.il.us
